### ISSUE TITLE
[GCC] PAD: Criação de um script para pre-build - Parte 2

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#371]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS iniciar a migração da estrutura inicial do MPAS para uma nova estrutura para o MONAN,
PARA dar suporte a tomada de decisão sobre definições futuras de desenvolvimento do MONAN e sua caracterização.

## :clipboard: Critérios de aceite de conclusão da Issue

FAzer os itens de 3.15 a 3.1.9 conforme o documento https://docs.google.com/document/d/1fDQhm2oyLRBZ0H1mybE41Of8aiiyQIhXn1QPyy-Ei2g/edit

- [x] 3.1.5
- [x] 3.1.6
- [x] 3.1.7
- [x] 3.1.8
- [x] 3.1.9

## :pencil: Detalhamento adicional da atividade

Realizar as tarefas listadas no documento citado acima

## :comet: Impactos

sem impactos significativos

## :link: Dependências

Dependência da parte 1,2,3 e 4

## :hammer_and_wrench: Solução

3.1.5 O script copyStruct faz a cópia
3.1.6 O único arquivo que usa os includes é src/core_init_atmosphere/mpas_init_atm_core_interface.F ele foi modificado para usar os módulos e é copiado quando a cópia é executada.
3.1.7 Essa etapa apresentou problemas listado em "Problemas Encontrados". Num primeiro momento um script foi criado para copiar as diretivas de CPP (#ifdef, etc) para as diretivas de fypp. 
3.1.8 Realizado. Mas foi necessário algumas intervenções. A compilação dos auxiliares esmf_time_f90, e SMIOL precisarm da intervenção no Makefile para que fosse introduzida a opção de include do MPI. Vai desaparecer quando usar o FPM.

---
Makefile do esmf_time.f90:
```makefile
.SUFFIXES: .F90 .o

OBJS = ESMF_AlarmClockMod.o \
	   ESMF_AlarmMod.o \
	   ESMF_BaseMod.o \
	   ESMF_BaseTimeMod.o \
	   ESMF_CalendarMod.o \
	   ESMF_ClockMod.o \
	   ESMF.o \
	   ESMF_FractionMod.o \
	   ESMF_ShrTimeMod.o \
	   ESMF_Stubs.o \
	   ESMF_TimeIntervalMod.o \
	   ESMF_TimeMod.o \
	   MeatMod.o \
	   wrf_error_fatal.o \
	   wrf_message.o

all: $(OBJS)
	ar -ru libesmf_time.a *.o

ESMF_AlarmClockMod.o: ESMF_AlarmMod.o ESMF_ClockMod.o ESMF_TimeIntervalMod.o ESMF_TimeMod.o

ESMF_AlarmMod.o: ESMF_BaseMod.o ESMF_TimeIntervalMod.o ESMF_TimeMod.o

ESMF_BaseMod.o:

ESMF_BaseTimeMod.o: ESMF_BaseMod.o

ESMF_CalendarMod.o: ESMF_BaseMod.o ESMF_BaseTimeMod.o

ESMF_ClockMod.o: ESMF_BaseMod.o ESMF_TimeIntervalMod.o ESMF_TimeMod.o ESMF_AlarmMod.o ESMF_TimeMod.o

ESMF.o: ESMF_AlarmMod.o ESMF_BaseMod.o ESMF_BaseTimeMod.o \
		ESMF_CalendarMod.o ESMF_ClockMod.o ESMF_FractionMod.o \
		ESMF_TimeIntervalMod.o ESMF_TimeMod.o ESMF_ShrTimeMod.o \
		ESMF_AlarmClockMod.o ESMF_Stubs.o MeatMod.o

ESMF_FractionMod.o:

ESMF_ShrTimeMod.o: ESMF_BaseMod.o ESMF_BaseTimeMod.o ESMF_CalendarMod.o

ESMF_Stubs.o: ESMF_BaseMod.o ESMF_CalendarMod.o

ESMF_TimeIntervalMod.o: ESMF_BaseMod.o ESMF_BaseTimeMod.o ESMF_FractionMod.o ESMF_CalendarMod.o ESMF
_ShrTimeMod.o

ESMF_TimeMod.o: ESMF_BaseMod.o ESMF_BaseTimeMod.o ESMF_TimeIntervalMod.o ESMF_CalendarMod.o ESMF_Shr
TimeMod.o ESMF_Stubs.o

MeatMod.o: ESMF_BaseMod.o

wrf_error_fatal.o:

wrf_message.o:

clean:
	rm -rf *.tmp.f90 *.o *.mod *.a

.F90.o:
	$(RM) $@ $*.mod
ifeq "$(GEN_F90)" "true"
	$(CPP) $(CPPFLAGS) $< > $*.tmp.f90 $(CPPINCLUDES) $(FCINCLUDES) -I.
	$(FC) $(FFLAGS) -c $*.tmp.f90 $(CPPINCLUDES) $(FCINCLUDES) -I.
else
	$(FC) $(CPPFLAGS) $(FFLAGS) -c $*.F90 $(CPPINCLUDES) $(FCINCLUDES) -I. -DHIDE_MPI
endif
```
---
Makefile do SMIOL:
```
override CPPINCLUDES += -DSMIOL_PNETCDF
CC = mpicc
FC = mpif90
CPPINCLUDES = /opt/gnu/includes

all: libsmiol.a libsmiolf.a

libsmiol.a: smiol.o smiol_utils.o
	ar -cr libsmiol.a smiol.o smiol_utils.o

libsmiolf.a: smiolf.o
	ar -cr libsmiolf.a smiolf.o

clean:
	$(RM) -f smiol.o smiol_utils.o libsmiol.a
	$(RM) -f smiolf.o smiolf.mod libsmiolf.a

# Cancel the built-in implicit rule for Modula-2 files (.mod) to avoid having 'make'
# try to create .o files from Fortran .mod files
%.o : %.mod

%.o : %.F90
	$(FC) $(CPPINCLUDES) $(FFLAGS) -c $<

%.o : %.c
	$(CC) $(CPPINCLUDES) $(CFLAGS) -c $<
```

3.1.9 Comecei os testes como FPM e esbarrei em algumas nuances do acesso a biblioteca MPI. É um problema que requer um pouco mais de estudo. Funciona! Mas será preciso usar uma forma de automatizar um pouco mais.

Adotou-se a estrutura com app, src. build é criado automaticamente!

Foi criado um toml para esmf_time:
```toml
name = "esmf_time"
version = "0.1.0"

 [build]
 external-modules = "mpi"

[dependencies]
mpi = "*"

[[executable]]
name = "esmf_time"

[fortran]
implicit-external=true
implicit-typing=true
```
Foi criado um toml para ezxml:

```toml
name = "ezxml"
version = "0.1.0"

 [build]
 external-modules = "mpi"

[dependencies]
mpi = "*"

[[executable]]
name = "ezxml"

[fortran]
implicit-external=true
implicit-typing=true
```
Foi criado um toml para SMIOL:

```toml
name = "SMIOL"
version = "0.1.0"

 [build]
 external-modules = "mpi"

[dependencies]
mpi = "*"

[[executable]]
name = "SMIOL"

[fortran]
implicit-external=true
implicit-typing=true
```

Para os códigos em tools será preciso revisar a forma de construir usando FPM pois há conflitos com bibliotecas e os mesmos tem programa principal em C. Os demais, em "external" só compõe bibliotecas.

## :rotating_light: Problemas encontrados

Os testes com cópia usando cpp, sem modificação, para filtragem dos fontes apresentou sério problema com alguns arquivos. A razão é que cpp foi feito para "C", apesar de tbm trabalhar com Fortran. Mas falha em certas condições do fonte fortran. Por exemplo: cpp se confunde em muitas linhas internas a laços de decisão se a mesma tem continuação (&).

## :white_check_mark: Conclusão

O código ficou muito mais legível pelos IDEs, como era esperado. As melhorias são sensíveis.

## :spiral_calendar: Trabalhos Futuros

- Trabalhar melhor no uso do FPM para encerrar a mudança.
- Inserir fypp ao invés do CPP.
