### ISSUE TITLE
[GCC] GRC: Git Actions CodeReviewer

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#536]
## :people_holding_hands: User Story

COMO (...)
QUEREMOS (...)
PARA (...)

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Testar CodeReviewer (0.1.0) com 1 arquivo usando GitAction

## :pencil: Detalhamento adicional da atividade

-.

## :comet: Impactos

-.

## :link: Dependências

-.

## :hammer_and_wrench: Solução

- Criado o arquivo **testaction.yml**
- Criado Action: https://github.com/GCC-DIMNT-CPTEC/codereviewer/actions/workflows/testaction.yml
- Utilizado como referência: https://www.geeksforgeeks.org/run-python-script-in-github-actions/

```
name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run Python script
        run: sudo apt install default-jre; make init; make test; python src/CodeReviewer.py tests/teste.F90
```

![Image](https://github.com/monanadmin/monan/assets/41485190/c048d673-e312-4fe5-8887-9695ca1e48d5)

## :rotating_light: Problemas encontrados

![Image](https://github.com/monanadmin/monan/assets/41485190/7f1242fc-8845-4e31-91f1-07b3c001da2c)

- Entender se a msg acima é um erro do Action ou do CodeReviewer.
- Realizado 3 commits direto na 'main', verificar o impacto disso no Git Flow e como trabalhar com o Action usando o Git Flow.

![Image](https://github.com/monanadmin/monan/assets/41485190/6843d635-2769-4b33-9d3c-fc964ccc6e37)

## :white_check_mark: Conclusão

- Montagem do GitAction realizado com 1 exemplo. Necessário entender o seu funcionamento agora.

## :spiral_calendar: Trabalhos Futuros

-.
